TRUNCATE owners;

insert into owners (firstName, lastName) values ('Keene', 'Peasegod');
insert into owners (firstName, lastName) values ('Gilles', 'Van Hove');
insert into owners (firstName, lastName) values ('Halley', 'Wedlake');
insert into owners (firstName, lastName) values ('Paxon', 'Sudworth');
insert into owners (firstName, lastName) values ('Kore', 'Beaver');
insert into owners (firstName, lastName) values ('Johny', 'Borsay');
insert into owners (firstName, lastName) values ('Linus', 'Storrah');
insert into owners (firstName, lastName) values ('Alphonse', 'Ponceford');
insert into owners (firstName, lastName) values ('Sharon', 'Haime');
insert into owners (firstName, lastName) values ('Opalina', 'Tidgewell');
insert into owners (firstName, lastName) values ('Janel', 'Frany');
insert into owners (firstName, lastName) values ('Jozef', 'Burg');
insert into owners (firstName, lastName) values ('Jerrome', 'Spradbrow');
insert into owners (firstName, lastName) values ('Raddie', 'Studde');
insert into owners (firstName, lastName) values ('Aubree', 'Fellgatt');
insert into owners (firstName, lastName) values ('Rachele', 'Mordaunt');
insert into owners (firstName, lastName) values ('Ephrem', 'Mawson');
insert into owners (firstName, lastName) values ('Maudie', 'Staff');
insert into owners (firstName, lastName) values ('Whitman', 'Firman');
insert into owners (firstName, lastName) values ('Evangelin', 'Giffin');
insert into owners (firstName, lastName) values ('Caron', 'Hopkins');
insert into owners (firstName, lastName) values ('Jone', 'Mustill');
insert into owners (firstName, lastName) values ('Issy', 'Suttell');
insert into owners (firstName, lastName) values ('Clair', 'Diggar');
insert into owners (firstName, lastName) values ('Eirena', 'Gornar');

TRUNCATE vehicles;

insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('GMC', 'Yukon', 2001, 'Green', 'AN69VNV', 23);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Porsche', '928', 1987, 'Turquoise', 'CY21AXK', 13);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('BMW', 'M3', 2003, 'Puce', 'PK78QFH', 9);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Chrysler', 'PT Cruiser', 2003, 'Red', 'JU58IWD', 7);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Mazda', 'Mazda3', 2009, 'Turquoise', 'AR70WSY', 18);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Oldsmobile', '98', 1996, 'Violet', 'NV22RWP', 5);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Chrysler', '300M', 2000, 'Khaki', 'EM88NDV', 13);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Mitsubishi', 'Outlander', 2004, 'Crimson', 'NY43SQD', 3);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('GMC', '2500 Club Coupe', 1995, 'Red', 'HK04AGI', 2);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Jaguar', 'XF', 2009, 'Goldenrod', 'OO93JOG', 10);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Chevrolet', '1500', 1993, 'Fuscia', 'XR90QMU', 7);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Maserati', 'Gran Sport', 2005, 'Turquoise', 'NH36EFK', 1);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Jeep', 'Compass', 2011, 'Violet', 'PT22OJM', 6);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Toyota', 'Tacoma Xtra', 2003, 'Green', 'ZY88TOA', 19);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Acura', 'NSX', 1995, 'Orange', 'EN68NGC', 3);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Ferrari', '599 GTB Fiorano', 2009, 'Maroon', 'OP23JWC', 11);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Ford', 'Focus', 2011, 'Turquoise', 'WL48RWL', 20);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Honda', 'Civic', 2002, 'Violet', 'LX84JBM', 2);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Ford', 'F350', 2010, 'Pink', 'HU94PEY', 21);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Lotus', 'Esprit Turbo', 1984, 'Aquamarine', 'VU81JBP', 20);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('BMW', '5 Series', 2001, 'Maroon', 'BZ55ADT', 16);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Volvo', 'S40', 2008, 'Orange', 'SN13LIF', 1);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Mitsubishi', 'Outlander', 2003, 'Pink', 'NI41VRX', 23);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Hyundai', 'Veracruz', 2011, 'Yellow', 'QM76HGE', 14);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Jeep', 'Cherokee', 1992, 'Aquamarine', 'TX68KJY', 14);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('GMC', 'Yukon', 2004, 'Goldenrod', 'MI25SBI', 23);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Cadillac', 'Escalade', 2002, 'Purple', 'CR90AYY', 8);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Pontiac', 'G5', 2009, 'Orange', 'LL98OGN', 11);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Ford', 'Mustang', 1965, 'Pink', 'RJ48AMF', 2);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Acura', 'TL', 1998, 'Indigo', 'FI98IPB', 2);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Lincoln', 'Blackwood', 2003, 'Aquamarine', 'PS98CVW', 6);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Ford', 'Country', 1967, 'Orange', 'OK43OYM', 20);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Volvo', 'V70', 2007, 'Mauv', 'PN42SIS', 14);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Chevrolet', 'Colorado', 2006, 'Orange', 'YE73QGN', 22);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Chevrolet', 'G-Series G30', 1995, 'Aquamarine', 'RZ06BGT', 25);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Mitsubishi', 'Lancer Evolution', 2003, 'Maroon', 'HT38WGP', 4);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Cadillac', 'Escalade', 1999, 'Pink', 'WL49NKI', 21);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Hyundai', 'Accent', 2013, 'Maroon', 'VX00AMU', 7);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Mercedes-Benz', 'C-Class', 2009, 'Aquamarine', 'RC21ERA', 13);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Chrysler', 'Town & Country', 2000, 'Red', 'ZC70DOW', 21);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Mitsubishi', 'Mighty Max', 1994, 'Puce', 'IC19ETF', 21);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('BMW', '525', 2004, 'Turquoise', 'ON48ZWG', 17);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Lamborghini', 'Murciélago', 2002, 'Turquoise', 'FX52IES', 22);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Cadillac', 'Catera', 1999, 'Purple', 'MR44EKK', 8);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Volvo', 'XC70', 2008, 'Yellow', 'ZW13GRC', 19);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Mercedes-Benz', 'SL65 AMG', 2006, 'Purple', 'OK26HYS', 14);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Chevrolet', 'Express 2500', 2000, 'Teal', 'VD99HDO', 13);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Mazda', '929', 1992, 'Puce', 'IJ77KPI', 18);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Chevrolet', 'Blazer', 1992, 'Puce', 'KS43HMS', 11);
insert into vehicles (make, model, modelYear, color, licensePlate, owner_id) values ('Mercury', 'Grand Marquis', 1996, 'Teal', 'XP71BJG', 12);
